### ISSUE TITLE
mopidy-deezer causes errors when used with mpd extension?

### ISSUE THREAD

**Issue by Shellfishgene** [rusty-dev/mopidy-deezer#12]
I recently started to get errors when using mopidy via the mpd interface. The mpd clients don't show songs in albums anymore, but show the artists and albums fine. This is for stuff in the local directory, however the errors below look like they originate in mopidy-deezer?

Aug 06 13:01:24 raspberrypi2 mopidy[9069]: INFO     New MPD connection from [::ffff:192.168.178.23]:50298
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: INFO     Searching Deezer for: {u'album': [u'Close Your Eyes CDS'], u'track_no': [u'1'], u'artist': [u'Bebel Gilberto']}
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: ERROR    Unhandled exception in MpdSession (urn:uuid:004a9847-bc9d-4d06-b817-720c62950d78):
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: Traceback (most recent call last):
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: response = self._handle_receive(message)
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 304, in _handle_receive
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: return self.on_receive(message)
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: File "/usr/lib/python2.7/dist-packages/mopidy/internal/network.py", line 369, in on_receive
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: self.on_line_received(line)
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: File "/usr/lib/python2.7/dist-packages/mopidy/mpd/session.py", line 34, in on_line_received
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: response = self.dispatcher.handle_request(line)
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: File "/usr/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 47, in handle_request
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: return self._call_next_filter(request, response, filter_chain)
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: File "/usr/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 69, in _call_next_filter
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: return next_filter(request, response, filter_chain)
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: File "/usr/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 77, in _catch_mpd_ack_errors_filter
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: return self._call_next_filter(request, response, filter_chain)
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: File "/usr/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 69, in _call_next_filter
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: return next_filter(request, response, filter_chain)
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: File "/usr/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 90, in _authenticate_filter
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: return self._call_next_filter(request, response, filter_chain)
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: File "/usr/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 69, in _call_next_filter
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: return next_filter(request, response, filter_chain)
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: File "/usr/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 106, in _command_list_filter
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: response = self._call_next_filter(request, response, filter_chain)
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: File "/usr/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 69, in _call_next_filter
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: return next_filter(request, response, filter_chain)
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: File "/usr/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 135, in _idle_filter
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: response = self._call_next_filter(request, response, filter_chain)
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: File "/usr/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 69, in _call_next_filter
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: return next_filter(request, response, filter_chain)
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: File "/usr/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 148, in _add_ok_filter
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: response = self._call_next_filter(request, response, filter_chain)
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: File "/usr/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 69, in _call_next_filter
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: return next_filter(request, response, filter_chain)
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: File "/usr/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 160, in _call_handler_filter
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: response = self._format_response(self._call_handler(request))
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: File "/usr/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 175, in _call_handler
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: return protocol.commands.call(tokens, context=self.context)
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: File "/usr/lib/python2.7/dist-packages/mopidy/mpd/protocol/__init__.py", line 180, in call
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: return self.handlers[tokens[0]](context, *tokens[1:])
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: File "/usr/lib/python2.7/dist-packages/mopidy/mpd/protocol/__init__.py", line 142, in validate
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: return func(*args, **kwargs)
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: File "/usr/lib/python2.7/dist-packages/mopidy/mpd/protocol/music_db.py", line 145, in find
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: results = context.core.library.search(query=query, exact=True).get()
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: compat.reraise(*self._data['exc_info'])
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: exec('raise tp, value, tb')
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: response = self._handle_receive(message)
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: return callee(*message['args'], **message['kwargs'])
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 347, in search
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: result = future.get()
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: compat.reraise(*self._data['exc_info'])
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: exec('raise tp, value, tb')
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: response = self._handle_receive(message)
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: return callee(*message['args'], **message['kwargs'])
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: File "/usr/local/lib/python2.7/dist-packages/mopidy_deezer/library.py", line 61, in search
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: artists, albums, tracks = self.backend.remote.search(query)
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: File "/usr/local/lib/python2.7/dist-packages/mopidy_deezer/deezer.py", line 152, in search
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: query = u' '.join(query['any'])
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: KeyError: 'any'
Aug 06 13:01:30 raspberrypi2 mopidy[9069]: Traceback (most recent call last):
Aug 06 13:01:30 raspberrypi2 mopidy[9069]: File "/usr/lib/python2.7/dist-packages/gi/overrides/GLib.py", line 702, in <lambda>
Aug 06 13:01:30 raspberrypi2 mopidy[9069]: func_fdtransform = lambda _, cond, *data: callback(channel, cond, *data)
Aug 06 13:01:30 raspberrypi2 mopidy[9069]: File "/usr/lib/python2.7/dist-packages/mopidy/internal/network.py", line 274, in recv_callback
Aug 06 13:01:30 raspberrypi2 mopidy[9069]: self.actor_ref.tell({'close': True})
Aug 06 13:01:30 raspberrypi2 mopidy[9069]: File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 398, in tell
Aug 06 13:01:30 raspberrypi2 mopidy[9069]: raise ActorDeadError('%s not found' % self)
Aug 06 13:01:30 raspberrypi2 mopidy[9069]: pykka.exceptions.ActorDeadError: MpdSession (urn:uuid:004a9847-bc9d-4d06-b817-720c62950d78) not found

**Comment by jjok** [comment]
I'm not sure on this one. Maybe someone with more knowledge of Mopidy can help?
@Jodel Can you tell what's happening here?

**Comment by jodal** [comment]
I think the key part in the stack trace is:

``` python
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: artists, albums, tracks = self.backend.remote.search(query)
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: File "/usr/local/lib/python2.7/dist-packages/mopidy_deezer/deezer.py", line 152, in search
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: query = u' '.join(query['any'])
Aug 06 13:01:25 raspberrypi2 mopidy[9069]: KeyError: 'any'
```

Mopidy-Deezer's `search()` method assumes that the search query will have a key named `any`. That isn't guaranteed.

**Comment by jjok** [comment]
@jodal Thanks. I'll see if I can look into it.

**Comment by rusty-dev** [comment]
Yeah, I remember, when writing this, I chose to just pick the "any" key because deezer doesn't support search by artist\album\track, the front-end I used at the time didn't support specific searches as well, so I left it like this.

**Comment by jjok** [comment]
I think we should be able to support `any`, `artist`, `album` and `track_name`.

**Comment by jjok** [comment]
@Shellfishgene What are you doing in the client to make it do that search?

```
{
    u'album': [u'Close Your Eyes CDS'],
    u'track_no': [u'1'],
    u'artist': [u'Bebel Gilberto']
}
```

Shouldn't `search()` only be called when the user is doing an actual search?

**Comment by Shellfishgene** [comment]
It didn't happen when searching, and only seemed to happen with GMPC, for example ncmpcpp was always fine. Not sure, I'll try to find out how to actually reproduce this.

**Comment by jjok** [comment]
It looks like it's just trying get the first track off that album, but I don't think it should be using the `search` method to do that.
Is it an issue with the client, rather than the extension?

**Comment by rusty-dev** [comment]
could be the client, I don't think supporting different types of search is mandatory, the client I used doesn't even have that option.

**Comment by Shellfishgene** [comment]
It may be the client, but Gnome Music Player Client is one of the most used ones I think. Also the problem with GMPC is that is seems to use search sometimes without the user actually searching. But the bug is there with all other clients, too, when the search function is used.

**Comment by jonas2515** [comment]
Deezer API actually supports searching for albums, artists and tracks. It's just a bit hidden in the api explorer.

The normal search query: http://api.deezer.com/search?q=greatstuff
For artists: http://api.deezer.com/search/artist?q=eminem
For albums: http://api.deezer.com/search/album?q=somealbum
And so on for tracks, playlists...

I'm surprised this thing is still working and nobody cares (spotify streaming clients here are really popular...).

**Comment by rusty-dev** [comment]
@jonas2515 I meant mopidy client that I uses, which didn't support search by artist\album\track.

Yeah, and looks like it's been that way from the start. Honestly, I'm more surprised that they implemented it this way in the first place. I mean, it's a simple token check before returning results, but no...

**Comment by jonas2515** [comment]
Ahh ok, I didn't look at the code and just guessed you were talking about the deezer api. :)

Well, we can't complain and as long as nobody (ab)uses this, maybe they just ignore it (or even hope for some publicity).
