### ISSUE TITLE
Moods broken

### ISSUE THREAD

**Issue by jjok** [rusty-dev/mopidy-deezer#15]
Trying to load "Moods" causes the following error.

```
2017-01-11 19:46:19,464 ERROR [1320:DeezerBackend-3] mopidy_deezer.deezer: Error during deezer api call, method: deezer.pageMoods, params: {'start': 0, 'nb': 100, 'type': 'playlist', 'genre_id': 0}, error: {u'MISSING_PARAMETER_ID': u'Parameter ID is missing'}
2017-01-11 19:46:19,467 ERROR [1320:Core-8] mopidy.core.library: DeezerBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 19, in _backend_error_handling
    yield
  File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 112, in _browse
    result = backend.library.browse(uri).get()
  File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/local/lib/python2.7/dist-packages/mopidy_deezer/library.py", line 49, in browse
    return browse_func()
  File "/usr/local/lib/python2.7/dist-packages/mopidy_deezer/deezer.py", line 282, in browse_moods
    for playlist in data['ITEMS']['data']:
KeyError: 'ITEMS'
```

It looks like the Moods functionality has been removed from Deezer, so we should just remove from the extension.

**Comment by bjo81** [comment]
Moods are still broken:
```
Jun 18 18:08:39 sipi mopidy[2747]: ERROR    Error during deezer api call, method: deezer.pageMoods, params: {'start': 0, 'nb': 100, 'type': 'playlist', 'genre_id': 0}, error: {u'MISSING_PARAMETER_ID': u'Parameter ID is missing'}
Jun 18 18:08:39 sipi mopidy[2747]: ERROR    DeezerBackend backend caused an exception.
Jun 18 18:08:39 sipi mopidy[2747]: Traceback (most recent call last):
Jun 18 18:08:39 sipi mopidy[2747]:   File "/usr/lib/python2.7/site-packages/mopidy/core/library.py", line 19, in _backend_error_handling
Jun 18 18:08:39 sipi mopidy[2747]:     yield
Jun 18 18:08:39 sipi mopidy[2747]:   File "/usr/lib/python2.7/site-packages/mopidy/core/library.py", line 112, in _browse
Jun 18 18:08:39 sipi mopidy[2747]:     result = backend.library.browse(uri).get()
Jun 18 18:08:39 sipi mopidy[2747]:   File "/usr/lib/python2.7/site-packages/pykka/future.py", line 299, in get
Jun 18 18:08:39 sipi mopidy[2747]:     exec('raise exc_info[0], exc_info[1], exc_info[2]')
Jun 18 18:08:39 sipi mopidy[2747]:   File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 200, in _actor_loop
Jun 18 18:08:39 sipi mopidy[2747]:     response = self._handle_receive(message)
Jun 18 18:08:39 sipi mopidy[2747]:   File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 294, in _handle_receive
Jun 18 18:08:39 sipi mopidy[2747]:     return callee(*message['args'], **message['kwargs'])
Jun 18 18:08:39 sipi mopidy[2747]:   File "/usr/lib/python2.7/site-packages/mopidy_deezer/library.py", line 49, in browse
Jun 18 18:08:39 sipi mopidy[2747]:     return browse_func()
Jun 18 18:08:39 sipi mopidy[2747]:   File "/usr/lib/python2.7/site-packages/mopidy_deezer/deezer.py", line 282, in browse_moods
Jun 18 18:08:39 sipi mopidy[2747]:     for playlist in data['ITEMS']['data']:
Jun 18 18:08:39 sipi mopidy[2747]: KeyError: 'ITEMS'
```

**Comment by jjok** [comment]
Yeah. It looks like the plan is to remove it (https://github.com/rusty-dev/mopidy-deezer/issues/14#issuecomment-271997768), but no one's done it yet.

**Comment by rusty-dev** [comment]
Yeah, deezer removed this feature, so it's not supposed to work. I just haven't been using mopidy for a long time, so I don't exactly have the incentive to remove it :)
