### ISSUE TITLE
Error in mopidy logs after starting with deezer backend

### ISSUE THREAD

**Issue by MurzNN** [rusty-dev/mopidy-deezer#18]
After starting mopidy with  deezer backend  I see those errors in logs:
```
2017-06-02 10:46:20,081 ERROR [28326:DeezerBackend-3] mopidy_deezer.deezer: Error during deezer api call, method: deezer.pageProfile, params: {'nb': 40, 'user_id': None, 'tab': 'playlists'}, error: {u'MISSING_PARAMETER_USER_ID': u'Parameter U
SER_ID is missing'}
2017-06-02 10:46:20,082 ERROR [28326:MainThread] mopidy.core.playlists: DeezerBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/core/playlists.py", line 18, in _backend_error_handling
    yield
  File "/usr/lib/python2.7/dist-packages/mopidy/core/playlists.py", line 66, in as_list
    playlists = future.get()
  File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/local/lib/python2.7/dist-packages/mopidy_deezer/playlists.py", line 23, in as_list
    self.refresh()
  File "/usr/local/lib/python2.7/dist-packages/mopidy_deezer/playlists.py", line 70, in refresh
    for playlist in self._backend.remote.browse_playlists():
  File "/usr/local/lib/python2.7/dist-packages/mopidy_deezer/deezer.py", line 247, in browse_playlists
    return data['TAB']['playlists']['data']
KeyError: 'TAB'
```
But seems module works normally. Is this critical errors?

**Comment by rusty-dev** [comment]
this is a consequence of not configuring your user id in settings, it's not a critical error. Check readme on how to configure user id.

**Comment by jjok** [comment]
@rusty-dev Should some features still work without setting a user ID? I don't think I've tried it before.

**Comment by rusty-dev** [comment]
Yes, only features that need user id won't work, like personal playlists in this case.

**Comment by MurzNN** [comment]
Thanks for description, all works normally with this error, so will be good to dismiss this error via simple check if user_id is set and skip this operation if no user_id filled in settings.
