### ISSUE TITLE
ImportError: No module named pathlib

### ISSUE THREAD

**Issue by pmishev** [rusty-dev/mopidy-deezer#20]
I get the following error when after running mopidy:

```
ERROR    Extension deezer failed during setup, this might have left the registry in a bad state.
Traceback (most recent call last):
  File "/home/pi/.python_virtual_envs/mopidy-dev/mopidy/mopidy/__main__.py", line 121, in main
    extension.setup(registry)
  File "/home/pi/.python_virtual_envs/mopidy/local/lib/python2.7/site-packages/mopidy_deezer/__init__.py", line 31, in setup
    from .actor import DeezerBackend
  File "/home/pi/.python_virtual_envs/mopidy/local/lib/python2.7/site-packages/mopidy_deezer/actor.py", line 10, in <module>
    from .deezer import DeezerClient
  File "/home/pi/.python_virtual_envs/mopidy/local/lib/python2.7/site-packages/mopidy_deezer/deezer.py", line 13, in <module>
    from eyed3.mp3.headers import Mp3Header, findHeader, timePerFrame
  File "/home/pi/.python_virtual_envs/mopidy/local/lib/python2.7/site-packages/eyed3/__init__.py", line 35, in <module>
    from .utils.log import log                                            # noqa
  File "/home/pi/.python_virtual_envs/mopidy/local/lib/python2.7/site-packages/eyed3/utils/__init__.py", line 23, in <module>
    import pathlib
ImportError: No module named pathlib
```

Do I need to manually install some dependency?

**Comment by pmishev** [comment]
Fixed by doing `sudo apt-get install python-pathlib`

**Comment by jjok** [comment]
Hmm. I don't know much about how dependencies should be handled in Python. Should `pathlib` be listed in `setup.py` or something?

**Comment by rusty-dev** [comment]
Looks like a missing dependency in `eyed3` library, not in this plugin.
